import { resolve } from "node:path";
import { existsSync, writeFileSync } from "node:fs";
import type { CellConfig } from "../config/cell-yaml-schema.js";

const GENERATED_MARKER = "<!-- generated by cell-cli -->";

function toTitleCase(name: string): string {
  return name
    .replace(/[-_]+/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

/**
 * Ensure index.html exists in the frontend directory.
 * Generates one from cell config if missing or if previously generated (has marker).
 * Returns true if a file was generated.
 */
export function ensureIndexHtml(
  frontendDir: string,
  config: CellConfig,
): boolean {
  const indexPath = resolve(frontendDir, "index.html");
  if (!config.frontend) return false;

  if (existsSync(indexPath)) {
    const content = Bun.file(indexPath).toString();
    if (!content.includes(GENERATED_MARKER)) {
      return false;
    }
  }

  const firstEntry = Object.values(config.frontend.entries)[0];
  const entrySrc = firstEntry?.src ?? "main.tsx";
  const title = toTitleCase(config.name);

  writeFileSync(
    indexPath,
    `${GENERATED_MARKER}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${title}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/${entrySrc}"></script>
  </body>
</html>
`,
  );
  return true;
}
