import { existsSync, mkdirSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { loadOtaviaYaml } from "../../config/load-otavia-yaml.js";
import { loadCellConfig } from "../../config/load-cell-yaml.js";
import { resolveCellDir } from "../../config/resolve-cell-dir.js";

export interface ViteDevHandle {
  stop: () => void;
}

/**
 * Start main frontend Vite dev server (single root MPA shell):
 * - root is apps/main/frontend
 * - dynamically loads each cell frontend via package exports ("@pkg/frontend")
 * - proxies API/OAuth requests to backend gateway with mount-aware rewrite
 * If no cell has frontend, returns a no-op stop.
 */
export async function startViteDev(
  rootDir: string,
  backendPort: number,
  vitePort: number
): Promise<ViteDevHandle> {
  const root = resolve(rootDir);
  const otavia = loadOtaviaYaml(root);
  const cellsWithFrontend: {
    mount: string;
    packageName: string;
    hasServiceWorker: boolean;
    swEntryPath?: string;
  }[] = [];

  for (const entry of otavia.cellsList) {
    const cellDir = resolveCellDir(root, entry.package);
    const cellYamlPath = resolve(cellDir, "cell.yaml");
    if (!existsSync(cellYamlPath)) continue;
    const config = loadCellConfig(cellDir);
    if (!config.frontend?.dir) continue;
    const hasServiceWorker = Boolean(config.frontend.entries?.sw?.entry);
    const swEntryPath =
      hasServiceWorker && config.frontend.entries?.sw?.entry
        ? resolve(cellDir, config.frontend.dir, config.frontend.entries.sw.entry).replace(/\\/g, "/")
        : undefined;
    cellsWithFrontend.push({ mount: entry.mount, packageName: entry.package, hasServiceWorker, swEntryPath });
  }

  if (cellsWithFrontend.length === 0) {
    console.log("[vite] No cells with frontend, skipping Vite dev server");
    return { stop: () => {} };
  }

  const frontendRoot = resolve(root, "frontend");
  if (!existsSync(frontendRoot)) {
    throw new Error(
      `main frontend root not found at ${frontendRoot}. Create apps/main/frontend first.`
    );
  }
  const srcDir = resolve(frontendRoot, "src");
  const generatedDir = resolve(srcDir, "generated");
  mkdirSync(generatedDir, { recursive: true });

  const generatedLoadersPath = resolve(generatedDir, "mount-loaders.ts");
  const firstMount = cellsWithFrontend[0].mount;
  const loadersSource = `// Auto-generated by otavia dev. Do not edit.
export const firstMount = ${JSON.stringify(firstMount)};
export const mounts = ${JSON.stringify(cellsWithFrontend.map((c) => c.mount))};
export const mountLoaders = {
${cellsWithFrontend
  .map((c) => `  ${JSON.stringify(c.mount)}: () => import(${JSON.stringify(`${c.packageName}/frontend`)}),`)
  .join("\n")}
} as Record<string, () => Promise<unknown>>;
`;
  writeFileSync(generatedLoadersPath, loadersSource, "utf-8");

  // Regenerate service worker proxy entries for cells that expose frontend/sw.
  for (const entryName of readdirSync(frontendRoot, { withFileTypes: true })) {
    if (!entryName.isDirectory()) continue;
    const mount = entryName.name;
    const dirPath = resolve(frontendRoot, mount);
    const swPath = resolve(dirPath, "sw.ts");
    const isKnownMount = cellsWithFrontend.some((c) => c.mount === mount);
    if (!isKnownMount && existsSync(swPath)) {
      rmSync(swPath, { force: true });
    }
  }
  for (const cell of cellsWithFrontend) {
    if (!cell.hasServiceWorker || !cell.swEntryPath) continue;
    const mountDir = resolve(frontendRoot, cell.mount);
    mkdirSync(mountDir, { recursive: true });
    const swProxyPath = resolve(mountDir, "sw.ts");
    const swProxySource = `// Auto-generated by otavia dev. Do not edit.
import ${JSON.stringify(`/@fs/${cell.swEntryPath}`)};
`;
    writeFileSync(swProxyPath, swProxySource, "utf-8");
  }

  const env = {
    ...process.env,
    OTAVIA_MOUNTS: JSON.stringify(cellsWithFrontend.map((c) => c.mount)),
    OTAVIA_FIRST_MOUNT: firstMount,
    VITE_PORT: String(vitePort),
    GATEWAY_BACKEND_PORT: String(backendPort),
  };

  const configPath = resolve(frontendRoot, "vite.config.ts");
  const child = Bun.spawn(["bun", "x", "vite", "--config", configPath], {
    cwd: frontendRoot,
    env,
    stdio: ["ignore", "inherit", "inherit"],
  });

  const stop = () => {
    child.kill();
  };

  child.exited.then((code) => {
    if (code !== 0 && code !== null) {
      console.error(`[vite] Process exited with code ${code}`);
    }
  });

  console.log(
    `[vite] Main frontend dev server starting at http://localhost:${vitePort} (mounts: ${cellsWithFrontend
      .map((c) => c.mount)
      .join(", ")})`
  );
  return { stop };
}
